import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AuthGuardService } from './service/auth-guard.service';



const routes: Routes = [
   { path: 'login', loadChildren: './pages/login/login.module#LoginPageModule' },
  { path: 'dashboard', canActivate: [AuthGuardService], loadChildren: './pages/home/home.module#HomePageModule'},
  { path: 'student', loadChildren: './pages/student/student.module#StudentPageModule' },
  { path: 'parents', loadChildren: './pages/parents/parents.module#ParentsPageModule' },
  { path: 'teacher', loadChildren: './pages/teacher/teacher.module#TeacherPageModule' },
  { path: 'subject', loadChildren: './pages/academic/subject/subject.module#SubjectPageModule' },
  { path: 'classes', loadChildren: './pages/academic/class/class.module#ClassPageModule' },
  { path: 'studentview/:studentID/:classID', loadChildren: './pages/studentview/studentview.module#StudentviewPageModule' },
  { path: 'parentsview/:parentsID', loadChildren: './pages/parentsview/parentsview.module#ParentsviewPageModule' },
  { path: 'teacherview/:teacherID', loadChildren: './pages/teacherview/teacherview.module#TeacherviewPageModule' },
  { path: 'routine', loadChildren: './pages/academic/routine/routine.module#RoutinePageModule' },
  { path: 'section', loadChildren: './pages/academic/section/section.module#SectionPageModule' },
  { path: 'assignment', loadChildren: './pages/academic/assignment/assignment.module#AssignmentPageModule' },
  { path: 'syllabus', loadChildren: './pages/academic/syllabus/syllabus.module#SyllabusPageModule' },
  { path: 'user', loadChildren: './pages/user/user.module#UserPageModule' },
    { path: 'userview/:userID', loadChildren: './pages/userview/userview.module#UserviewPageModule' },
    { path: 'sattendance', loadChildren: './pages/attendance/sattendance/sattendance.module#SattendancePageModule' },
  { path: 'tattendance', loadChildren: './pages/attendance/tattendance/tattendance.module#TattendancePageModule' },
  { path: 'uattendance', loadChildren: './pages/attendance/uattendance/uattendance.module#UattendancePageModule' },
  { path: 'exam', loadChildren: './pages/exam/exam/exam.module#ExamPageModule' },
  { path: 'examschedule', loadChildren: './pages/exam/examschedule/examschedule.module#ExamschedulePageModule' },
  { path: 'grade', loadChildren: './pages/exam/grade/grade.module#GradePageModule' },
  { path: 'mark', loadChildren: './pages/mark/mark/mark.module#MarkPageModule' },
    { path: 'markview/:studentID/:classID', loadChildren: './pages/mark/markview/markview.module#MarkviewPageModule' },
    { path: 'markpercentage', loadChildren: './pages/mark/markdistribution/markdistribution.module#MarkdistributionPageModule' },
  { path: 'sattendanceview/:studentID/:classID',
      loadChildren: './pages/attendance/sattendanceview/sattendanceview.module#SattendanceviewPageModule' },
  { path: 'tattendanceview/:teacherID',
      loadChildren: './pages/attendance/tattendanceview/tattendanceview.module#TattendanceviewPageModule' },
  { path: 'uattendanceview/:userID', loadChildren: './pages/attendance/uattendanceview/uattendanceview.module#UattendanceviewPageModule' },
  { path: 'question_group', loadChildren: './pages/onlineexam/questiongroup/questiongroup.module#QuestiongroupPageModule' },
  { path: 'question_level', loadChildren: './pages/onlineexam/questionlevel/questionlevel.module#QuestionlevelPageModule' },
  { path: 'question_bank', loadChildren: './pages/onlineexam/questionbank/questionbank.module#QuestionbankPageModule' },
    { path: 'questionbankview/:questionbankID',
        loadChildren: './pages/onlineexam/questionbank/questionbankview/questionbankview.module#QuestionbankviewPageModule' },
    { path: 'online_exam', loadChildren: './pages/onlineexam/onlineexam.module#OnlineexamPageModule' },
  { path: 'instruction', loadChildren: './pages/onlineexam/instruction/instruction.module#InstructionPageModule' },
  { path: 'takeexam', loadChildren: './pages/onlineexam/takeexam/takeexam.module#TakeexamPageModule' },
  { path: 'salary_template', loadChildren: './pages/payroll/salarytemplate/salarytemplate.module#SalarytemplatePageModule' },
  { path: 'hourly_template', loadChildren: './pages/payroll/hourlytemplate/hourlytemplate.module#HourlytemplatePageModule' },
  { path: 'managesalary', loadChildren: './pages/payroll/managesalary/managesalary.module#ManagesalaryPageModule' },
  { path: 'makepayment', loadChildren: './pages/payroll/makepayment/makepayment.module#MakepaymentPageModule' },
  { path: 'salarytemplateview/:salarytemplateID',
      loadChildren: './pages/payroll/salarytemplateview/salarytemplateview.module#SalarytemplateviewPageModule' },
    { path: 'vendor', loadChildren: './pages/assetmanagement/vendor/vendor.module#VendorPageModule' },
  { path: 'location', loadChildren: './pages/assetmanagement/location/location.module#LocationPageModule' },
  { path: 'asset_category', loadChildren: './pages/assetmanagement/assetcategory/assetcategory.module#AssetcategoryPageModule' },
  { path: 'asset', loadChildren: './pages/assetmanagement/asset/asset.module#AssetPageModule' },
  { path: 'asset_assignment', loadChildren: './pages/assetmanagement/assetassignment/assetassignment.module#AssetassignmentPageModule' },
  { path: 'purchase', loadChildren: './pages/assetmanagement/purchase/purchase.module#PurchasePageModule' },
  { path: 'assetassignmentview/:assetassignmentID',
      loadChildren: './pages/assetmanagement/assetassignmentview/assetassignmentview.module#AssetassignmentviewPageModule' },
  { path: 'productcategory', loadChildren: './pages/inventory/category/category.module#CategoryPageModule' },
  { path: 'product', loadChildren: './pages/inventory/product/product.module#ProductPageModule' },
  { path: 'productwarehouse', loadChildren: './pages/inventory/warehouse/warehouse.module#WarehousePageModule' },
  { path: 'productsupplier', loadChildren: './pages/inventory/supplier/supplier.module#SupplierPageModule' },
  { path: 'productpurchase', loadChildren: './pages/inventory/productpurchases/productpurchases.module#ProductpurchasesPageModule' },
  { path: 'productsale', loadChildren: './pages/inventory/sale/sale.module#SalePageModule' },
  { path: 'leavecategory', loadChildren: './pages/leaveapplication/leavecategory/leavecategory.module#LeavecategoryPageModule' },
  { path: 'leaveassign', loadChildren: './pages/leaveapplication/leaveassign/leaveassign.module#LeaveassignPageModule' },
  { path: 'leaveapply', loadChildren: './pages/leaveapplication/leaveapply/leaveapply.module#LeaveapplyPageModule' },
  { path: 'leaveapplication',
      loadChildren: './pages/leaveapplication/leaveapplication/leaveapplication.module#LeaveapplicationPageModule' },
  { path: 'activitiescategory', loadChildren: './pages/child/activitscategory/activitscategory.module#ActivitscategoryPageModule' },
  { path: 'activities', loadChildren: './pages/child/activities/activities.module#ActivitiesPageModule' },
  { path: 'childcare', loadChildren: './pages/child/childecare/childecare.module#ChildecarePageModule' },
  { path: 'leaveapplyview/:leaveapplicationID',
      loadChildren: './pages/leaveapplication/leaveapplyview/leaveapplyview.module#LeaveapplyviewPageModule' },
  { path: 'leaveapplicationview/:applicationID',
      loadChildren: './pages/leaveapplication/leaveapplicationview/leaveapplicationview.module#LeaveapplicationviewPageModule' },
  { path: 'lmember', loadChildren: './pages/library/member/member.module#MemberPageModule' },
  { path: 'book', loadChildren: './pages/library/books/books.module#BooksPageModule' },
  { path: 'transport', loadChildren: './pages/transport/transport/transport.module#TransportPageModule' },
  { path: 'tmember', loadChildren: './pages/transport/tmember/tmember.module#TmemberPageModule' },
  { path: 'memberview/:studentID/:classID', loadChildren: './pages/library/memberview/memberview.module#MemberviewPageModule' },
  { path: 'tmemberview/:studentID/:classID', loadChildren: './pages/transport/tmemberview/tmemberview.module#TmemberviewPageModule' },
  { path: 'hostel', loadChildren: './pages/hostel/hostel/hostel.module#HostelPageModule' },
  { path: 'category', loadChildren: './pages/hostel/hostalcategory/hostalcategory.module#HostalcategoryPageModule' },
  { path: 'hmember', loadChildren: './pages/hostel/hmember/hmember.module#HmemberPageModule' },
  { path: 'hmemberview/:studentID/:classID', loadChildren: './pages/hostel/hmemberview/hmemberview.module#HmemberviewPageModule' },
  { path: 'feetypes', loadChildren: './pages/account/feetypes/feetypes.module#FeetypesPageModule' },
  { path: 'paymenthistory', loadChildren: './pages/account/paymenthistory/paymenthistory.module#PaymenthistoryPageModule' },
  { path: 'expense', loadChildren: './pages/account/expense/expense.module#ExpensePageModule' },
  { path: 'income', loadChildren: './pages/account/income/income.module#IncomePageModule' },
  { path: 'notice', loadChildren: './pages/announcement/notice/notice.module#NoticePageModule' },
  { path: 'event', loadChildren: './pages/announcement/event/event.module#EventPageModule' },
  { path: 'holiday', loadChildren: './pages/announcement/holiday/holiday.module#HolidayPageModule' },
  { path: 'noticeview/:noticeID', loadChildren: './pages/announcement/noticeview/noticeview.module#NoticeviewPageModule' },
  { path: 'eventview/:eventID', loadChildren: './pages/announcement/eventview/eventview.module#EventviewPageModule' },
  { path: 'holidayview/:holidayID', loadChildren: './pages/announcement/holidayview/holidayview.module#HolidayviewPageModule' },
  { path: 'visitorinfo', loadChildren: './pages/visitorinfo/visitorinfo/visitorinfo.module#VisitorinfoPageModule' },
  { path: 'visitorinfoview/:visitorID',
      loadChildren: './pages/visitorinfo/visitorinfoview/visitorinfoview.module#VisitorinfoviewPageModule' },
  { path: 'schoolyear', loadChildren: './pages/administrator/academicyear/academicyear.module#AcademicyearPageModule' },
  { path: 'studentgroup', loadChildren: './pages/administrator/studentgroup/studentgroup.module#StudentgroupPageModule' },
  { path: 'complain', loadChildren: './pages/administrator/complain/complain.module#ComplainPageModule' },
  { path: 'certificate_template',
      loadChildren: './pages/administrator/certificatetemplate/certificatetemplate.module#CertificatetemplatePageModule' },
  { path: 'systemadmin', loadChildren: './pages/administrator/systemadmin/systemadmin.module#SystemadminPageModule' },
  { path: 'sociallink', loadChildren: './pages/administrator/socillink/socillink.module#SocillinkPageModule' },
  { path: 'mailandsmstemplate',
      loadChildren: './pages/administrator/mailandsmstemplate/mailandsmstemplate.module#MailandsmstemplatePageModule' },
  { path: 'usertype', loadChildren: './pages/administrator/usertype/usertype.module#UsertypePageModule' },
  { path: 'update', loadChildren: './pages/administrator/update/update.module#UpdatePageModule' },
  { path: 'posts_categories', loadChildren: './pages/frontend/postcategorie/postcategorie.module#PostcategoriePageModule' },
  { path: 'posts', loadChildren: './pages/frontend/posts/posts.module#PostsPageModule' },
  { path: 'pages', loadChildren: './pages/frontend/pages/pages.module#PagesPageModule' },
  { path: 'complainview/:complainID', loadChildren: './pages/administrator/complainview/complainview.module#ComplainviewPageModule' },
  { path: 'systemadminview/:userID',
      loadChildren: './pages/administrator/systemadminview/systemadminview.module#SystemadminviewPageModule' },
  { path: 'mailandsmstemplateview/:mailandsmstemplateID',
      loadChildren: './pages/administrator/mailandsmstemplateview/mailandsmstemplateview.module#MailandsmstemplateviewPageModule' },
  { path: 'certificatetemplateview/:certificate_templateID',
      loadChildren: './pages/administrator/certificatetemplateview/certificatetemplateview.module#CertificatetemplateviewPageModule' },
  { path: 'sattendanceadd', loadChildren: './pages/attendance/sattendanceadd/sattendanceadd.module#SattendanceaddPageModule' },
  { path: 'tattendanceadd', loadChildren: './pages/attendance/tattendanceadd/tattendanceadd.module#TattendanceaddPageModule' },
  { path: 'uattendanceadd', loadChildren: './pages/attendance/uattendanceadd/uattendanceadd.module#UattendanceaddPageModule' },
  { path: 'mailandsms', loadChildren: './pages/maillsms/maillsms.module#MaillsmsPageModule' },
  { path: 'maillsmsview/:mailsmsID', loadChildren: './pages/maillsms/maillsmsview/maillsmsview.module#MaillsmsviewPageModule' },
  { path: 'invoice', loadChildren: './pages/account/invoice/invoice.module#InvoicePageModule' },
  { path: 'invoiceview/:invoiceID', loadChildren: './pages/account/invoice/invoiceview/invoiceview.module#InvoiceviewPageModule' },
  { path: 'productpurchasesview/:purchaseID',
      loadChildren: './pages/inventory/productpurchases/productpurchasesview/productpurchasesview.module#ProductpurchasesviewPageModule' },
  { path: 'saleview/:saleID', loadChildren: './pages/inventory/sale/saleview/saleview.module#SaleviewPageModule' },
  { path: 'assetview/:assetID', loadChildren: './pages/assetmanagement/asset/assetview/assetview.module#AssetviewPageModule' },
  { path: 'instructionview/:instructionID',
      loadChildren: './pages/onlineexam/instruction/instructionview/instructionview.module#InstructionviewPageModule' },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule {}
